export const urlConstants2 = {
    // BASE_URL:'http://10.202.26.14:8000',
    // BASE_URL:'http://13.251.136.133:8000',
      // BASE_URL:'http://localhost:8000',
      BASE_URL: 'http://172.31.0.236:8000/',
      // BASE_URL:'https://demo.mysmartsmc.com:8000',
      SITE_URL:'/api',
      TRENDS_URL:'/trends/',
      TRENDS_READ_CATEGORY:'read-categories/',
      TRENDS_READ_SUBCATEGORY:'read-sub-categories/',
  
      MCAFEE:'/mcafee',
      TECH_HIPS:'/hips/',
      SOLARWINDS:'/solarwinds',
      TECH_SYS_MGMT:'/sys-mgmt/',
      FIREMON:'/firemon',
      TECH_SECURITY_MANAGER:'/security-manager/',
      SYMANTEC:'/symantec',
      TECH_ANTIVIRUS:'/antivirus/',
      F5_URL:'/f5',
      TECH_LOAD_BALANCER:'/load-balancer/',
      AWS_URL:'/aws',
      TECH_S3_URL:'/s3/',
      TECH_EC2_URL:'/ec2/',
      SERVICENOW:'/servicenow',
      TECH_CMDB:'/cmdb/',
      TECH_TICKETING:'/ticketing/',
      TECH_URL_AV:'/av/',
      TECH_DRIVE_ENCRYPTION:'/drive-encryption/',
      TECH_DLP_URL:'/dlp/',
      TECH_DLP_DISCOVER:'/dlp-discover/',
      TECH_DLP_ENDPOINT:'/dlp-endpoint/',
      PEOPLE_URL:'/people',
      USECASE_COMPLIANCE:'/compliance',
      WEIGHTAGE_URL:'/smc-admin/',
      ADMIN_URL:'/admin',
      TECH_WEIGHTAGE: '/tech-weightage/',
      TRENDS_WRITE_URL:'/write-tech',
      
      AUTH_LOGIN_URL: '/v1/auth/login/',
      AUTH_PASSWORD_CHANGE_URL: '/v1/auth/password-change/',
      AUTH_TOKEN_VERIFY_URL: '/v1/auth/token-verify/',
      AUTH_TOKEN_REFRESH_URL: '/v1/auth/token-refresh/',
  
      FILTER_START_DATE:'startDate',
      FILTER_END_DATE:'endDate',
  };
  